# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # NPM dependencies - Root
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "fboiero"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # NPM dependencies - Web
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "fboiero"
    labels:
      - "dependencies"
      - "npm"
      - "web"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # NPM dependencies - Circuits
  - package-ecosystem: "npm"
    directory: "/circuits"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "fboiero"
    labels:
      - "dependencies"
      - "npm"
      - "circuits"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # NPM dependencies - SDK
  - package-ecosystem: "npm"
    directory: "/sdk"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "fboiero"
    labels:
      - "dependencies"
      - "npm"
      - "sdk"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Cargo dependencies - Soroban
  - package-ecosystem: "cargo"
    directory: "/soroban"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "fboiero"
    labels:
      - "dependencies"
      - "rust"
      - "soroban"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Cargo dependencies - Contracts
  - package-ecosystem: "cargo"
    directory: "/contracts"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "fboiero"
    labels:
      - "dependencies"
      - "rust"
      - "contracts"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "fboiero"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"

  # Docker
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "fboiero"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker)"
